#!/bin/busybox sh

if test "$0" = "sh"; then
  /bin/busybox sh "$@";
elif test "$1" = "sh"; then
  /bin/busybox "$@";
else
  if test -x /system/bin/busybox ; then
    /system/bin/busybox $0 "$@";
  elif test -x /system/xbin/busybox ; then
    /system/xbin/busybox $0 "$@";
  else
    /bin/busybox $0 "$@";
  fi;
fi;
